apiVersion: apps/v1
kind: Deployment
metadata:
  name: o-ran-interface-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: o-ran-interface
  replicas: 1
  template:
    metadata:
      labels:
        app: o-ran-interface
    spec:
      containers:
        - name: o-ran-interface
          image: {{ .Values.image.repository }}/{{ .Values.image.name}}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ACCELCRD_VERSION
            value: {{ .Values.accelerator.customResource.version }}
          - name: ACCELCRD_NAMESPACE
            value: {{ .Values.accelerator.customResource.namespace }}
          - name: ACCELCRD_NAME
            value: {{ .Values.accelerator.customResource.name }}
          - name: ACCELCRD_NAME_PLURAL
            value: {{ .Values.accelerator.customResource.pluralName }}
          - name: ACCELCRD_GROUP
            value: {{ .Values.accelerator.customResource.group }}
          - name: HAMCRD_VERSION
            value: {{ .Values.ham.customResource.version }}
          - name: HAMCRD_NAMESPACE
            value: {{ .Values.ham.customResource.namespace }}
          - name: HAMCRD_NAME
            value: {{ .Values.ham.customResource.name }}
          - name: HAMCRD_NAME_PLURAL
            value: {{ .Values.ham.customResource.pluralName }}
          - name: HAMCRD_GROUP
            value: {{ .Values.ham.customResource.group }}
          - name: INTERFACE_SVC_NAME
            value: {{ .Values.svc.interface.name }}
          - name: IMS_ENDPOINT
            value: {{ .Values.ims.endpoint }}
          - name: LOG_DIRECTORY
            value: "{{ .Values.logging.directory }}"
          - name: FAULT_SUBSCRIPTION_NAME
            value: "fault-subscriptions"
          ports:
          - containerPort: 5000
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", ". /scripts/utils/post_start.sh"]
