apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fault-subscription-reader-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: fault-subscription-reader
  apiGroup: rbac.authorization.k8s.io