apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fault-subscription-reader
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["fault-subscriptions"]
  verbs: ["get", "list", "update", "delete"]