apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.interface.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: o-ran-interface
  ports:
    - port: 5000
      targetPort: 5000
