namespace: default

image:
  repository: localhost
  name: o-ran-interface
  pullPolicy: Never
  tag: "latest"

accelerator:
  customResource:
    version: "v1"
    namespace: "default"
    name: "accelclusterconfig"
    pluralName: "accelclusterconfigs"
    group: "accel.example.com"
    verbs: ["get", "watch", "list", "patch"]

ham:
  customResource:
    version: "v1"
    namespace: "default"
    name: "hamconfig"
    pluralName: "hamconfigs"
    group: "accel.example.com"
    verbs: ["get", "watch", "list", "patch"]

svc:
  interface:
    name: "o-ran-interface-svc"
ims:
  endpoint: ""

logging:
  directory: "/scripts/logs"