apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hamconfigs.accel.example.com
spec:
  group: accel.example.com
  scope: Namespaced
  names:
    plural: hamconfigs
    singular: hamconfig
    kind: hamconfig
    shortNames:
    - hc
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                aalHam:
                  type: object
                  properties:
                    registrationServiceEndpoint:
                      description: The service endpoint that the HAM uses register with the IMS in order for the IMS to connect to and manage the HAM
                      type: string
                    localServiceEndpoint:
                      description: The service endpoint that the HAM exposes to the IMS that permits the IMS to send requests to the HAM and receive notifications from the HAM
                      type: string
            status:
              type: object
              properties:
                aalHam:
                  type: object
                  properties:
                    operationalState:
                      description: Reflects the HAM's operational state as defined in clause 7.1.1 of ITU X.731
                      enum:
                        - DISABLED
                        - ENABLED
                      default: DISABLED
                      type: string
                    imsRegistrationState:
                      description: Reflects the registration state of HAM toward the IMS
                      enum:
                        - NOTREGISTERED
                        - REGISTERED
                      default: NOTREGISTERED
                      type: string
                    localServiceEndpoint:
                      description: The service endpoint that the HAM exposes to the IMS that permits the IMS to send requests to the HAM and receive notifications from the HAM
                      type: string
                    registrationServiceEndpoint:
                      description: The service endpoint that the HAM uses register with the IMS in order for the IMS to connect to and manage the HAM
                      type: string
